# This configuration file tells GraphQL Code Generator how
# to generate types based on our schema.
schema: './src/graphql/schema.graphql'
generates:
  # Specify where our generated types should live.
  ./src/graphql/generated/schema.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      skipTypename: true
      # contextType: '../../types#ContextEntity'
      mappers: { 'Profile': '../../types#ProfileEntity' }
